
version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=drpuser
      - POSTGRES_PASSWORD=Brasil92535842
      - POSTGRES_DB=drpdb
